python -u run.py \
    --task_name long_term_forecast \
    --is_training 1 \
    --root_path ./dataset/electricity/ \
    --data_path electricity.csv \
    --model_id ECL_96_96 \
    --model $model_name \
    --data custom \
    --features S \
    --seq_len 96 \
    --label_len 48 \
    --pred_len 96 \
    --num_layers 2 \
    --memory_units 4 \
    --memory_dim 128 \
    --d_model 128 \
    --dropout 0 \
    --memory_connectivity 0.2 \
    --enc_in 1 \
    --dec_in 1 \
    --c_out 1 \
    --des 'Exp' \
    --itr 1